/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TestSerialMsg'
 * message type.
 */

public class TestSerialMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 137;

    /** Create a new TestSerialMsg of size 4. */
    public TestSerialMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TestSerialMsg of the given data_length. */
    public TestSerialMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg with the given data_length
     * and base offset.
     */
    public TestSerialMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store.
     */
    public TestSerialMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TestSerialMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TestSerialMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg embedded in the given message
     * at the given base offset.
     */
    public TestSerialMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg embedded in the given message
     * at the given base offset and length.
     */
    public TestSerialMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TestSerialMsg> \n";
      try {
        s += "  [period=0x"+Long.toHexString(get_period())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [lifetime=0x"+Long.toHexString(get_lifetime())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: period
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'period' is signed (false).
     */
    public static boolean isSigned_period() {
        return false;
    }

    /**
     * Return whether the field 'period' is an array (false).
     */
    public static boolean isArray_period() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'period'
     */
    public static int offset_period() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'period'
     */
    public static int offsetBits_period() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'period'
     */
    public int get_period() {
        return (int)getUIntBEElement(offsetBits_period(), 16);
    }

    /**
     * Set the value of the field 'period'
     */
    public void set_period(int value) {
        setUIntBEElement(offsetBits_period(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'period'
     */
    public static int size_period() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'period'
     */
    public static int sizeBits_period() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: lifetime
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'lifetime' is signed (false).
     */
    public static boolean isSigned_lifetime() {
        return false;
    }

    /**
     * Return whether the field 'lifetime' is an array (false).
     */
    public static boolean isArray_lifetime() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'lifetime'
     */
    public static int offset_lifetime() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'lifetime'
     */
    public static int offsetBits_lifetime() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'lifetime'
     */
    public int get_lifetime() {
        return (int)getUIntBEElement(offsetBits_lifetime(), 16);
    }

    /**
     * Set the value of the field 'lifetime'
     */
    public void set_lifetime(int value) {
        setUIntBEElement(offsetBits_lifetime(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'lifetime'
     */
    public static int size_lifetime() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'lifetime'
     */
    public static int sizeBits_lifetime() {
        return 16;
    }

}
